/**
 * Route path constants, grouped by role. Both the router (src/router/) and
 * any component that needs to link/navigate (including the AI assistant's
 * quick-action suggestions) import from here — never hard-code a path
 * string inline, so a route rename is a one-file change.
 */
export const publicRoutes = {
  home: "/",
  about: "/about",
  howItWorks: "/how-it-works",
  findTailor: "/find-a-tailor",
  findDesigner: "/find-a-designer",
  vendorMarketplace: "/marketplace",
  professionalProfile: (id: string) => `/professionals/${id}`,
  productDetails: (id: string) => `/products/${id}`,
  pricing: "/pricing",
  contact: "/contact",
  terms: "/terms",
  privacy: "/privacy",
  help: "/help",
} as const;

export const authRoutes = {
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  callback: "/auth/callback",
} as const;

export const customerRoutes = {
  dashboard: "/app/customer",
  orders: "/app/customer/orders",
  orderDetails: (id: string) => `/app/customer/orders/${id}`,
  trackOrder: (id: string) => `/app/customer/orders/${id}/track`,
  findProfessionals: "/app/customer/find",
  professionalDetails: (id: string) => `/app/customer/professionals/${id}`,
  createOrder: (professionalId: string) => `/app/customer/professionals/${professionalId}/order`,
  measurements: "/app/customer/measurements",
  designs: "/app/customer/designs",
  cart: "/app/customer/cart",
  checkout: "/app/customer/checkout",
  payment: (orderId: string) => `/app/customer/orders/${orderId}/payment`,
  paymentSuccess: "/app/customer/payment/success",
  paymentFailed: "/app/customer/payment/failed",
  invoices: "/app/customer/invoices",
  invoiceDetails: (id: string) => `/app/customer/invoices/${id}`,
  reviews: "/app/customer/reviews",
  favorites: "/app/customer/favorites",
  notifications: "/app/customer/notifications",
  messages: "/app/customer/messages",
  profile: "/app/customer/profile",
  addresses: "/app/customer/addresses",
  settings: "/app/customer/settings",
} as const;

export const professionalRoutes = {
  dashboard: "/app/professional",
  orders: "/app/professional/orders",
  orderDetails: (id: string) => `/app/professional/orders/${id}`,
  production: "/app/professional/production",
  customers: "/app/professional/customers",
  customerDetails: (id: string) => `/app/professional/customers/${id}`,
  measurements: "/app/professional/measurements",
  designs: "/app/professional/designs",
  portfolio: "/app/professional/portfolio",
  services: "/app/professional/services",
  vendorMarketplace: "/app/professional/vendor-marketplace",
  vendorProductDetails: (id: string) => `/app/professional/vendor-marketplace/products/${id}`,
  cart: "/app/professional/cart",
  checkout: "/app/professional/checkout",
  vendorOrders: "/app/professional/vendor-orders",
  vendorOrderDetails: (id: string) => `/app/professional/vendor-orders/${id}`,
  delivery: "/app/professional/delivery",
  trackDelivery: (id: string) => `/app/professional/delivery/${id}/track`,
  invoices: "/app/professional/invoices",
  payments: "/app/professional/payments",
  reviews: "/app/professional/reviews",
  verification: "/app/professional/verification",
  location: "/app/professional/location",
  messages: "/app/professional/messages",
  notifications: "/app/professional/notifications",
  profile: "/app/professional/profile",
  settings: "/app/professional/settings",
} as const;

export const vendorRoutes = {
  dashboard: "/app/vendor",
  orders: "/app/vendor/orders",
  orderDetails: (id: string) => `/app/vendor/orders/${id}`,
  products: "/app/vendor/products",
  addProduct: "/app/vendor/products/new",
  editProduct: (id: string) => `/app/vendor/products/${id}/edit`,
  productDetails: (id: string) => `/app/vendor/products/${id}`,
  categories: "/app/vendor/categories",
  inventory: "/app/vendor/inventory",
  delivery: "/app/vendor/delivery",
  trackDelivery: (id: string) => `/app/vendor/delivery/${id}/track`,
  invoices: "/app/vendor/invoices",
  payments: "/app/vendor/payments",
  verification: "/app/vendor/verification",
  profile: "/app/vendor/profile",
  notifications: "/app/vendor/notifications",
  settings: "/app/vendor/settings",
} as const;

export const deliveryRoutes = {
  dashboard: "/app/delivery",
  requests: "/app/delivery/requests",
  active: "/app/delivery/active",
  details: (id: string) => `/app/delivery/${id}`,
  pickup: (id: string) => `/app/delivery/${id}/pickup`,
  navigation: (id: string) => `/app/delivery/${id}/navigate`,
  dropoff: (id: string) => `/app/delivery/${id}/dropoff`,
  history: "/app/delivery/history",
  earnings: "/app/delivery/earnings",
  verification: "/app/delivery/verification",
  profile: "/app/delivery/profile",
  notifications: "/app/delivery/notifications",
  settings: "/app/delivery/settings",
} as const;

export const adminRoutes = {
  dashboard: "/app/admin",
  users: "/app/admin/users",
  customers: "/app/admin/customers",
  professionals: "/app/admin/professionals",
  vendors: "/app/admin/vendors",
  deliveryPartners: "/app/admin/delivery-partners",
  orders: "/app/admin/orders",
  payments: "/app/admin/payments",
  invoices: "/app/admin/invoices",
  deliveries: "/app/admin/deliveries",
  kyc: "/app/admin/kyc",
  kyb: "/app/admin/kyb",
  reviews: "/app/admin/reviews",
  disputes: "/app/admin/disputes",
  reports: "/app/admin/reports",
  auditLogs: "/app/admin/audit-logs",
  notifications: "/app/admin/notifications",
  settings: "/app/admin/settings",
} as const;
